"""

Revision ID: 7ad12898579a
Revises: a7fa7de6234e
Create Date: 2023-08-09 15:07:10.668626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad12898579a'
down_revision: Union[str, None] = 'a7fa7de6234e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('time', sa.String(), nullable=True))
    op.create_foreign_key(None, 'artists', 'genres', ['genre_id'], ['id'])
    op.drop_column('artists', 'genre')
    op.add_column('genres', sa.Column('genre', sa.String(), nullable=True))
    op.drop_column('genres', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('genres', 'genre')
    op.add_column('artists', sa.Column('genre', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'time')
    # ### end Alembic commands ###
