"""1

Revision ID: a7fa7de6234e
Revises: 7e385ca340f9
Create Date: 2023-08-08 20:55:53.547060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fa7de6234e'
down_revision: Union[str, None] = '7e385ca340f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artists', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('stage', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artists', 'genres', ['genre_id'], ['id'])
    op.drop_column('artists', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genre', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'stage')
    op.drop_column('artists', 'genre_id')
    op.drop_table('genres')
    # ### end Alembic commands ###
