"""empty message

Revision ID: fd50b45f89a2
Revises: 814492964d5a
Create Date: 2023-08-09 16:27:32.354829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd50b45f89a2'
down_revision: Union[str, None] = '814492964d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artists', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artists', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'genre_id')
    op.drop_table('genres')
    # ### end Alembic commands ###
